---

- name: Build systemd image
  hosts: localhost
  tags: systemd
  tasks:
    - shell: packer build -only='build-systemd.docker.debian' .

- name: Build lighttpd image
  hosts: localhost
  tags: lighttpd
  tasks:
    - shell: packer build -only='build-lighttpd.docker.debian-systemd' .

- name: Build multiservice image
  hosts: localhost
  tags: multiservice
  tasks:
    - shell: packer build -only='build-multiservice.docker.debian-systemd' .
